[build]
  command = "npm run build:web"
  functions = "netlify/functions"
  publish = "dist/client"
  
[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max_old_space_size=8192"
  NPM_FLAGS = "--legacy-peer-deps"  # Helps with dependency resolution

[build.processing]
  skip_processing = true  # Skip Netlify's default processing

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 404

[functions]
  # Include everything to ensure dynamic routes can be used.
  included_files = ["dist/server/**/*"]

[[headers]]
  for = "/dist/server/_expo/functions/*"
  [headers.values]
    # Set to 60 seconds as an example.
    "Cache-Control" = "public, max-age=60, s-maxage=60"